# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/goho.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protobufs/goho.proto\x12\x04goho\".\n\x0c\x43onfirmation\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\"Q\n\x04User\x12\x0e\n\x06userid\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x15\n\rhome_location\x18\x04 \x01(\t\" \n\x0eGetUserRequest\x12\x0e\n\x06userid\x18\x01 \x01(\x05\"z\n\x04Ride\x12\x0e\n\x06rideid\x18\x01 \x01(\x05\x12\r\n\x05rider\x18\x02 \x01(\x05\x12\x0e\n\x06\x64river\x18\x03 \x01(\x05\x12\x13\n\x0b\x64\x65stination\x18\x04 \x01(\t\x12\x10\n\x08location\x18\x05 \x01(\t\x12\x0c\n\x04time\x18\x06 \x01(\t\x12\x0e\n\x06status\x18\x07 \x01(\t\" \n\x0eGetRideRequest\x12\x0e\n\x06rideid\x18\x01 \x01(\x05\"%\n\x13GetUserRidesRequest\x12\x0e\n\x06userid\x18\x01 \x01(\x05\x32\xb0\x02\n\x0bGoHoService\x12-\n\x07GetUser\x12\x14.goho.GetUserRequest\x1a\n.goho.User\"\x00\x12+\n\x07\x41\x64\x64User\x12\n.goho.User\x1a\x12.goho.Confirmation\"\x00\x12-\n\x07GetRide\x12\x14.goho.GetRideRequest\x1a\n.goho.Ride\"\x00\x12+\n\x07\x41\x64\x64Ride\x12\n.goho.Ride\x1a\x12.goho.Confirmation\"\x00\x12.\n\nUpdateRide\x12\n.goho.Ride\x1a\x12.goho.Confirmation\"\x00\x12\x39\n\x0cGetUserRides\x12\x19.goho.GetUserRidesRequest\x1a\n.goho.Ride\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobufs.goho_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONFIRMATION._serialized_start=30
  _CONFIRMATION._serialized_end=76
  _USER._serialized_start=78
  _USER._serialized_end=159
  _GETUSERREQUEST._serialized_start=161
  _GETUSERREQUEST._serialized_end=193
  _RIDE._serialized_start=195
  _RIDE._serialized_end=317
  _GETRIDEREQUEST._serialized_start=319
  _GETRIDEREQUEST._serialized_end=351
  _GETUSERRIDESREQUEST._serialized_start=353
  _GETUSERRIDESREQUEST._serialized_end=390
  _GOHOSERVICE._serialized_start=393
  _GOHOSERVICE._serialized_end=697
# @@protoc_insertion_point(module_scope)
